# This is a configuration file for Xnat Download Upload UI .
# If you dont know what you are doing, please dont modify this file.
# Config for XnatDUI.py 

#############
#
#
#############

sys-init:
  host: "https://cerebra.nida.nih.gov"
  #parallel processing with multi-threading(T) or multi-processing (P) - Two possible values T or P. P - uses spreads it across multiple cores.
  # P uses multiple CPU cores - more compute intensive. T - uses multi threads. 
  parallel: "P"
  #Maximum number of parallel threads/cores. Minimum value: 2. Giving it 1, it won't execute the child thread/process
  max-parallel: 8
  #Projects to remove from dropdown box
  proj2rm:
    - "000"
    - "Demographics"
    - "NRB_6_21_14"
  convprogs:
    - "Dimon"
    - "to3d"
    - "dcm2nii"
    - "dcm2niix"
  scan-quality:
    - "usable"
    - "unknown"
    - "questionable"
    - "unusable"
  # path where to store xnat cache, logfiles & app cache. Each value a directory name
  cache-location: 
    - "~"
    - ".xnat-dui-cache"
  #Log level to store in logfile
  loglevel: "detail" #Possible values: detail , short
  #Colors used in tables to identify duplicate fields
  colors:
    - "#FFFFCC"
    - "#CCFFCC"
    - "#CCFFFF"
    - "#CCFFFF"
    - "#E0E0E0"
    - "#FFCCCC"
    - "#FFE5CC"
    - "#E5FFCC"
    - "#CCFFE5"
    - "#CCCCFF"
    - "#FFCCE5"

down-init:
  nfs-mnt: "/.NFS/xnat"
  pathprefix-linux: "/prot/%PROJ%"
  pathprefix-win: "C:\\Temp\\%PROJ%"
  fileprefix: "%SCAN%"
  resprefix: "%RES%"
  cmbpath:
    - "PROJ"
    - "SUBJ"
    - "SESS"
    - "SCAN"
    - "RES"
  cleanup:
    - "dimon.files"
    - "GERT_Reco"
upload-init:
  res_names:
    - "MRSI"
    - "TASKDATA"