# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xnatdui.ui'
#
# Created: Tue Feb 28 10:00:33 2017
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_XnatDUI(object):
    def setupUi(self, XnatDUI):
        XnatDUI.setObjectName(_fromUtf8("XnatDUI"))
        XnatDUI.resize(790, 786)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(XnatDUI.sizePolicy().hasHeightForWidth())
        XnatDUI.setSizePolicy(sizePolicy)
        XnatDUI.setMinimumSize(QtCore.QSize(780, 576))
        self.centralWidget = QtGui.QWidget(XnatDUI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_host = QtGui.QLabel(self.centralWidget)
        self.lbl_host.setObjectName(_fromUtf8("lbl_host"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_host)
        self.edt_host = QtGui.QLineEdit(self.centralWidget)
        self.edt_host.setObjectName(_fromUtf8("edt_host"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_host)
        self.lbl_username = QtGui.QLabel(self.centralWidget)
        self.lbl_username.setObjectName(_fromUtf8("lbl_username"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_username)
        self.edt_username = QtGui.QLineEdit(self.centralWidget)
        self.edt_username.setObjectName(_fromUtf8("edt_username"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.edt_username)
        self.lbl_pwd = QtGui.QLabel(self.centralWidget)
        self.lbl_pwd.setObjectName(_fromUtf8("lbl_pwd"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_pwd)
        self.edt_pwd = QtGui.QLineEdit(self.centralWidget)
        self.edt_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.edt_pwd.setObjectName(_fromUtf8("edt_pwd"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.edt_pwd)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.line)
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.line_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.btn_SignIn = QtGui.QPushButton(self.centralWidget)
        self.btn_SignIn.setObjectName(_fromUtf8("btn_SignIn"))
        self.horizontalLayout_10.addWidget(self.btn_SignIn)
        self.lbl_status = QtGui.QLabel(self.centralWidget)
        self.lbl_status.setStyleSheet(_fromUtf8("background-color: #ffffcc;"))
        self.lbl_status.setText(_fromUtf8(""))
        self.lbl_status.setObjectName(_fromUtf8("lbl_status"))
        self.horizontalLayout_10.addWidget(self.lbl_status)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.line_3 = QtGui.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cmb_project = QtGui.QComboBox(self.centralWidget)
        self.cmb_project.setObjectName(_fromUtf8("cmb_project"))
        self.verticalLayout_6.addWidget(self.cmb_project)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_refresh = QtGui.QPushButton(self.centralWidget)
        self.btn_refresh.setObjectName(_fromUtf8("btn_refresh"))
        self.horizontalLayout_4.addWidget(self.btn_refresh)
        self.btn_reset = QtGui.QPushButton(self.centralWidget)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.horizontalLayout_4.addWidget(self.btn_reset)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_4 = QtGui.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grp_what = QtGui.QGroupBox(self.centralWidget)
        self.grp_what.setTitle(_fromUtf8(""))
        self.grp_what.setObjectName(_fromUtf8("grp_what"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.grp_what)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.rb_what_download = QtGui.QRadioButton(self.grp_what)
        self.rb_what_download.setObjectName(_fromUtf8("rb_what_download"))
        self.horizontalLayout_5.addWidget(self.rb_what_download)
        self.rb_what_upload = QtGui.QRadioButton(self.grp_what)
        self.rb_what_upload.setObjectName(_fromUtf8("rb_what_upload"))
        self.horizontalLayout_5.addWidget(self.rb_what_upload)
        self.verticalLayout_4.addWidget(self.grp_what)
        self.grp_download_method = QtGui.QGroupBox(self.centralWidget)
        self.grp_download_method.setTitle(_fromUtf8(""))
        self.grp_download_method.setFlat(False)
        self.grp_download_method.setObjectName(_fromUtf8("grp_download_method"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.grp_download_method)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rb_down_https = QtGui.QRadioButton(self.grp_download_method)
        self.rb_down_https.setObjectName(_fromUtf8("rb_down_https"))
        self.horizontalLayout_3.addWidget(self.rb_down_https)
        self.rb_down_nfs = QtGui.QRadioButton(self.grp_download_method)
        self.rb_down_nfs.setObjectName(_fromUtf8("rb_down_nfs"))
        self.horizontalLayout_3.addWidget(self.rb_down_nfs)
        self.verticalLayout_4.addWidget(self.grp_download_method)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_5 = QtGui.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_page1 = QtGui.QPushButton(self.centralWidget)
        self.btn_page1.setObjectName(_fromUtf8("btn_page1"))
        self.horizontalLayout.addWidget(self.btn_page1)
        self.btn_page2 = QtGui.QPushButton(self.centralWidget)
        self.btn_page2.setObjectName(_fromUtf8("btn_page2"))
        self.horizontalLayout.addWidget(self.btn_page2)
        self.btn_page3 = QtGui.QPushButton(self.centralWidget)
        self.btn_page3.setObjectName(_fromUtf8("btn_page3"))
        self.horizontalLayout.addWidget(self.btn_page3)
        self.btn_page4 = QtGui.QPushButton(self.centralWidget)
        self.btn_page4.setObjectName(_fromUtf8("btn_page4"))
        self.horizontalLayout.addWidget(self.btn_page4)
        self.btn_page5 = QtGui.QPushButton(self.centralWidget)
        self.btn_page5.setObjectName(_fromUtf8("btn_page5"))
        self.horizontalLayout.addWidget(self.btn_page5)
        self.toolButton = QtGui.QToolButton(self.centralWidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_6 = QtGui.QFrame(self.centralWidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_2.addWidget(self.line_6)
        self.stackedWidget = QtGui.QStackedWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 175))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_0 = QtGui.QWidget()
        self.page_0.setObjectName(_fromUtf8("page_0"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.page_0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.lbl_qotd = QtGui.QLabel(self.page_0)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_qotd.setFont(font)
        self.lbl_qotd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_qotd.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_qotd.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_qotd.setObjectName(_fromUtf8("lbl_qotd"))
        self.verticalLayout_18.addWidget(self.lbl_qotd)
        self.lbl_qotd_text = QtGui.QLabel(self.page_0)
        self.lbl_qotd_text.setObjectName(_fromUtf8("lbl_qotd_text"))
        self.verticalLayout_18.addWidget(self.lbl_qotd_text)
        self.line_8 = QtGui.QFrame(self.page_0)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_18.addWidget(self.line_8)
        self.dial = QtGui.QDial(self.page_0)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayout_18.addWidget(self.dial)
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lbl_sub = QtGui.QLabel(self.page_1)
        self.lbl_sub.setObjectName(_fromUtf8("lbl_sub"))
        self.verticalLayout_8.addWidget(self.lbl_sub)
        self.lineEdit_2 = QtGui.QLineEdit(self.page_1)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_8.addWidget(self.lineEdit_2)
        self.listWidget = QtGui.QListWidget(self.page_1)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_8.addWidget(self.listWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lbl_sess = QtGui.QLabel(self.page_1)
        self.lbl_sess.setObjectName(_fromUtf8("lbl_sess"))
        self.verticalLayout_9.addWidget(self.lbl_sess)
        self.lineEdit = QtGui.QLineEdit(self.page_1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_9.addWidget(self.lineEdit)
        self.treeWidget_2 = QtGui.QTreeWidget(self.page_1)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_9.addWidget(self.treeWidget_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lbl_scan = QtGui.QLabel(self.page_1)
        self.lbl_scan.setObjectName(_fromUtf8("lbl_scan"))
        self.verticalLayout_7.addWidget(self.lbl_scan)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chk_usable = QtGui.QCheckBox(self.page_1)
        self.chk_usable.setObjectName(_fromUtf8("chk_usable"))
        self.horizontalLayout_7.addWidget(self.chk_usable)
        self.chk_unknown = QtGui.QCheckBox(self.page_1)
        self.chk_unknown.setObjectName(_fromUtf8("chk_unknown"))
        self.horizontalLayout_7.addWidget(self.chk_unknown)
        self.chk_questionable = QtGui.QCheckBox(self.page_1)
        self.chk_questionable.setObjectName(_fromUtf8("chk_questionable"))
        self.horizontalLayout_7.addWidget(self.chk_questionable)
        self.chk_unusable = QtGui.QCheckBox(self.page_1)
        self.chk_unusable.setObjectName(_fromUtf8("chk_unusable"))
        self.horizontalLayout_7.addWidget(self.chk_unusable)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.treeWidget = QtGui.QTreeWidget(self.page_1)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_7.addWidget(self.treeWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.grp_send = QtGui.QGroupBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send.sizePolicy().hasHeightForWidth())
        self.grp_send.setSizePolicy(sizePolicy)
        self.grp_send.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_send.setTitle(_fromUtf8(""))
        self.grp_send.setObjectName(_fromUtf8("grp_send"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.grp_send)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.edt_path_txt = QtGui.QLineEdit(self.grp_send)
        self.edt_path_txt.setObjectName(_fromUtf8("edt_path_txt"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.edt_path_txt)
        self.btn_send_edt = QtGui.QPushButton(self.grp_send)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_edt.sizePolicy().hasHeightForWidth())
        self.btn_send_edt.setSizePolicy(sizePolicy)
        self.btn_send_edt.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_edt.setObjectName(_fromUtf8("btn_send_edt"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.btn_send_edt)
        self.cmb_path_txt = QtGui.QComboBox(self.grp_send)
        self.cmb_path_txt.setObjectName(_fromUtf8("cmb_path_txt"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.cmb_path_txt)
        self.btn_send_cmb = QtGui.QPushButton(self.grp_send)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_cmb.sizePolicy().hasHeightForWidth())
        self.btn_send_cmb.setSizePolicy(sizePolicy)
        self.btn_send_cmb.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_cmb.setObjectName(_fromUtf8("btn_send_cmb"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.btn_send_cmb)
        self.horizontalLayout_9.addLayout(self.formLayout_2)
        self.gridFrame = QtGui.QFrame(self.grp_send)
        self.gridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.gridLayout = QtGui.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_reset_path_selected = QtGui.QPushButton(self.gridFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_selected.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_selected.setSizePolicy(sizePolicy)
        self.btn_reset_path_selected.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_selected.setObjectName(_fromUtf8("btn_reset_path_selected"))
        self.gridLayout.addWidget(self.btn_reset_path_selected, 0, 0, 1, 1)
        self.btn_reset_path_all = QtGui.QPushButton(self.gridFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_all.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_all.setSizePolicy(sizePolicy)
        self.btn_reset_path_all.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_all.setObjectName(_fromUtf8("btn_reset_path_all"))
        self.gridLayout.addWidget(self.btn_reset_path_all, 1, 0, 1, 1)
        self.btn_mk_bids = QtGui.QPushButton(self.gridFrame)
        self.btn_mk_bids.setObjectName(_fromUtf8("btn_mk_bids"))
        self.gridLayout.addWidget(self.btn_mk_bids, 0, 1, 1, 1)
        self.chk_BIDS_extra = QtGui.QCheckBox(self.gridFrame)
        self.chk_BIDS_extra.setObjectName(_fromUtf8("chk_BIDS_extra"))
        self.gridLayout.addWidget(self.chk_BIDS_extra, 1, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.gridFrame)
        self.verticalLayout_10.addWidget(self.grp_send)
        self.grp_send_path_loc = QtGui.QGroupBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send_path_loc.sizePolicy().hasHeightForWidth())
        self.grp_send_path_loc.setSizePolicy(sizePolicy)
        self.grp_send_path_loc.setObjectName(_fromUtf8("grp_send_path_loc"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.grp_send_path_loc)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.rb_send_path = QtGui.QRadioButton(self.grp_send_path_loc)
        self.rb_send_path.setObjectName(_fromUtf8("rb_send_path"))
        self.horizontalLayout_8.addWidget(self.rb_send_path)
        self.rb_send_file = QtGui.QRadioButton(self.grp_send_path_loc)
        self.rb_send_file.setObjectName(_fromUtf8("rb_send_file"))
        self.horizontalLayout_8.addWidget(self.rb_send_file)
        self.verticalLayout_10.addWidget(self.grp_send_path_loc)
        self.grp_path = QtGui.QGroupBox(self.page_2)
        self.grp_path.setObjectName(_fromUtf8("grp_path"))
        self.layout_path_outer = QtGui.QVBoxLayout(self.grp_path)
        self.layout_path_outer.setObjectName(_fromUtf8("layout_path_outer"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chk_path_select_all_path = QtGui.QCheckBox(self.grp_path)
        self.chk_path_select_all_path.setObjectName(_fromUtf8("chk_path_select_all_path"))
        self.horizontalLayout_11.addWidget(self.chk_path_select_all_path)
        self.chk_path_select_all_filename = QtGui.QCheckBox(self.grp_path)
        self.chk_path_select_all_filename.setObjectName(_fromUtf8("chk_path_select_all_filename"))
        self.horizontalLayout_11.addWidget(self.chk_path_select_all_filename)
        self.layout_path_outer.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10.addWidget(self.grp_path)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.listWidget_2 = QtGui.QListWidget(self.page_3)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.horizontalLayout_13.addWidget(self.listWidget_2)
        self.listWidget_5 = QtGui.QListWidget(self.page_3)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.horizontalLayout_13.addWidget(self.listWidget_5)
        self.listWidget_4 = QtGui.QListWidget(self.page_3)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        self.horizontalLayout_13.addWidget(self.listWidget_4)
        self.listWidget_3 = QtGui.QListWidget(self.page_3)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.horizontalLayout_13.addWidget(self.listWidget_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rb_dcm = QtGui.QRadioButton(self.groupBox_2)
        self.rb_dcm.setObjectName(_fromUtf8("rb_dcm"))
        self.gridLayout_2.addWidget(self.rb_dcm, 0, 0, 1, 1)
        self.rb_afni = QtGui.QRadioButton(self.groupBox_2)
        self.rb_afni.setObjectName(_fromUtf8("rb_afni"))
        self.gridLayout_2.addWidget(self.rb_afni, 1, 0, 1, 1)
        self.rb_nifti = QtGui.QRadioButton(self.groupBox_2)
        self.rb_nifti.setObjectName(_fromUtf8("rb_nifti"))
        self.gridLayout_2.addWidget(self.rb_nifti, 0, 1, 1, 1)
        self.rb_custom = QtGui.QRadioButton(self.groupBox_2)
        self.rb_custom.setObjectName(_fromUtf8("rb_custom"))
        self.gridLayout_2.addWidget(self.rb_custom, 1, 1, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.edt_down_status = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edt_down_status.setFont(font)
        self.edt_down_status.setObjectName(_fromUtf8("edt_down_status"))
        self.verticalLayout_13.addWidget(self.edt_down_status)
        self.edt_down_cmd = QtGui.QLineEdit(self.groupBox)
        self.edt_down_cmd.setObjectName(_fromUtf8("edt_down_cmd"))
        self.verticalLayout_13.addWidget(self.edt_down_cmd)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.btn_refresh_cmd = QtGui.QPushButton(self.groupBox)
        self.btn_refresh_cmd.setObjectName(_fromUtf8("btn_refresh_cmd"))
        self.verticalLayout_12.addWidget(self.btn_refresh_cmd)
        self.btn_download = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download.setFont(font)
        self.btn_download.setAutoFillBackground(False)
        self.btn_download.setObjectName(_fromUtf8("btn_download"))
        self.verticalLayout_12.addWidget(self.btn_download)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.treeWidget_3 = QtGui.QTreeWidget(self.page_4)
        self.treeWidget_3.setObjectName(_fromUtf8("treeWidget_3"))
        self.treeWidget_3.headerItem().setText(0, _fromUtf8("1"))
        self.horizontalLayout_15.addWidget(self.treeWidget_3)
        self.frame_3 = QtGui.QFrame(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_15.addWidget(self.radioButton)
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_15.addWidget(self.comboBox)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_16.addWidget(self.radioButton_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_16.addWidget(self.lineEdit_3)
        self.btn_up_res = QtGui.QPushButton(self.groupBox_4)
        self.btn_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_up_res.setObjectName(_fromUtf8("btn_up_res"))
        self.verticalLayout_16.addWidget(self.btn_up_res)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_14.addWidget(self.groupBox_4)
        self.btn_upload = QtGui.QPushButton(self.frame_3)
        self.btn_upload.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upload.setFont(font)
        self.btn_upload.setObjectName(_fromUtf8("btn_upload"))
        self.verticalLayout_14.addWidget(self.btn_upload)
        self.horizontalLayout_15.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_7 = QtGui.QFrame(self.centralWidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout.addWidget(self.line_7)
        self.pb_inter = QtGui.QProgressBar(self.centralWidget)
        self.pb_inter.setProperty("value", 24)
        self.pb_inter.setObjectName(_fromUtf8("pb_inter"))
        self.verticalLayout.addWidget(self.pb_inter)
        self.pb_final = QtGui.QProgressBar(self.centralWidget)
        self.pb_final.setProperty("value", 24)
        self.pb_final.setObjectName(_fromUtf8("pb_final"))
        self.verticalLayout.addWidget(self.pb_final)
        self.tab_logger = QtGui.QTabWidget(self.centralWidget)
        self.tab_logger.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.tab_logger.setObjectName(_fromUtf8("tab_logger"))
        self.tab_short = QtGui.QWidget()
        self.tab_short.setObjectName(_fromUtf8("tab_short"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_short)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.txt_browser_short = QtGui.QTextBrowser(self.tab_short)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_browser_short.sizePolicy().hasHeightForWidth())
        self.txt_browser_short.setSizePolicy(sizePolicy)
        self.txt_browser_short.setObjectName(_fromUtf8("txt_browser_short"))
        self.verticalLayout_3.addWidget(self.txt_browser_short)
        self.tab_logger.addTab(self.tab_short, _fromUtf8(""))
        self.tab_detailed = QtGui.QWidget()
        self.tab_detailed.setObjectName(_fromUtf8("tab_detailed"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_detailed)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.txt_browser_detailed = QtGui.QTextBrowser(self.tab_detailed)
        self.txt_browser_detailed.setObjectName(_fromUtf8("txt_browser_detailed"))
        self.verticalLayout_5.addWidget(self.txt_browser_detailed)
        self.tab_logger.addTab(self.tab_detailed, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_logger)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        XnatDUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(XnatDUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        XnatDUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(XnatDUI)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        XnatDUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(XnatDUI)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        XnatDUI.setStatusBar(self.statusBar)

        self.retranslateUi(XnatDUI)
        self.stackedWidget.setCurrentIndex(0)
        self.tab_logger.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(XnatDUI)

    def retranslateUi(self, XnatDUI):
        XnatDUI.setWindowTitle(QtGui.QApplication.translate("XnatDUI", "XnatDUI", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_host.setText(QtGui.QApplication.translate("XnatDUI", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_username.setText(QtGui.QApplication.translate("XnatDUI", "Username :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pwd.setText(QtGui.QApplication.translate("XnatDUI", "Password :", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_SignIn.setText(QtGui.QApplication.translate("XnatDUI", "Sign In", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refresh.setText(QtGui.QApplication.translate("XnatDUI", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset.setText(QtGui.QApplication.translate("XnatDUI", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_what_download.setText(QtGui.QApplication.translate("XnatDUI", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_what_upload.setText(QtGui.QApplication.translate("XnatDUI", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_down_https.setText(QtGui.QApplication.translate("XnatDUI", "via HTTPS", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_down_nfs.setText(QtGui.QApplication.translate("XnatDUI", "via NFS", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page1.setText(QtGui.QApplication.translate("XnatDUI", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page2.setText(QtGui.QApplication.translate("XnatDUI", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page3.setText(QtGui.QApplication.translate("XnatDUI", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page4.setText(QtGui.QApplication.translate("XnatDUI", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page5.setText(QtGui.QApplication.translate("XnatDUI", "Run Process", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("XnatDUI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_qotd.setText(QtGui.QApplication.translate("XnatDUI", "Random Ron Swanson Quote:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_qotd_text.setText(QtGui.QApplication.translate("XnatDUI", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sub.setText(QtGui.QApplication.translate("XnatDUI", "Select Subjects", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sess.setText(QtGui.QApplication.translate("XnatDUI", "Select Sessions", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_scan.setText(QtGui.QApplication.translate("XnatDUI", "Select Scans", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_usable.setText(QtGui.QApplication.translate("XnatDUI", "Usable", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_unknown.setText(QtGui.QApplication.translate("XnatDUI", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_questionable.setText(QtGui.QApplication.translate("XnatDUI", "Questionable", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_unusable.setText(QtGui.QApplication.translate("XnatDUI", "Unusable", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send_edt.setText(QtGui.QApplication.translate("XnatDUI", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send_cmb.setText(QtGui.QApplication.translate("XnatDUI", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_path_selected.setText(QtGui.QApplication.translate("XnatDUI", "Reset Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_path_all.setText(QtGui.QApplication.translate("XnatDUI", "Reeset All", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mk_bids.setText(QtGui.QApplication.translate("XnatDUI", "Make BIDS Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_BIDS_extra.setText(QtGui.QApplication.translate("XnatDUI", "Download BIDS", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_send_path_loc.setTitle(QtGui.QApplication.translate("XnatDUI", "Where to Send", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_send_path.setText(QtGui.QApplication.translate("XnatDUI", "Send to PATH name", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_send_file.setText(QtGui.QApplication.translate("XnatDUI", "Send to FILE name", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_path.setTitle(QtGui.QApplication.translate("XnatDUI", "Create Unique Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_path_select_all_path.setText(QtGui.QApplication.translate("XnatDUI", "Check/Uncheck All PATHs", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_path_select_all_filename.setText(QtGui.QApplication.translate("XnatDUI", "Check/Uncheck All Filenames", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("XnatDUI", "Select Format", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_dcm.setText(QtGui.QApplication.translate("XnatDUI", "DICOM", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_afni.setText(QtGui.QApplication.translate("XnatDUI", "AFNI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_nifti.setText(QtGui.QApplication.translate("XnatDUI", "NIFTI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_custom.setText(QtGui.QApplication.translate("XnatDUI", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("XnatDUI", "Conversion Script", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_down_status.setText(QtGui.QApplication.translate("XnatDUI", "Status: Ready", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refresh_cmd.setText(QtGui.QApplication.translate("XnatDUI", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_download.setText(QtGui.QApplication.translate("XnatDUI", "   DOWNLOAD  ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("XnatDUI", "Resource Name", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("XnatDUI", "Select Existing Type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("XnatDUI", "Create New Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_up_res.setText(QtGui.QApplication.translate("XnatDUI", "Create New Resource", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_upload.setText(QtGui.QApplication.translate("XnatDUI", "UPLOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_logger.setTabText(self.tab_logger.indexOf(self.tab_short), QtGui.QApplication.translate("XnatDUI", "Short Logger", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_logger.setTabText(self.tab_logger.indexOf(self.tab_detailed), QtGui.QApplication.translate("XnatDUI", "Detailed Logger", None, QtGui.QApplication.UnicodeUTF8))

