# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xnatdui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XnatDUI(object):
    def setupUi(self, XnatDUI):
        XnatDUI.setObjectName("XnatDUI")
        XnatDUI.resize(790, 786)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(XnatDUI.sizePolicy().hasHeightForWidth())
        XnatDUI.setSizePolicy(sizePolicy)
        XnatDUI.setMinimumSize(QtCore.QSize(780, 576))
        XnatDUI.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(XnatDUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(11, 0, 11, 0)
        self.formLayout.setSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.lbl_host = QtWidgets.QLabel(self.frame)
        self.lbl_host.setObjectName("lbl_host")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_host)
        self.edt_host = QtWidgets.QLineEdit(self.frame)
        self.edt_host.setObjectName("edt_host")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edt_host)
        self.lbl_username = QtWidgets.QLabel(self.frame)
        self.lbl_username.setObjectName("lbl_username")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.edt_username = QtWidgets.QLineEdit(self.frame)
        self.edt_username.setObjectName("edt_username")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_username)
        self.lbl_pwd = QtWidgets.QLabel(self.frame)
        self.lbl_pwd.setObjectName("lbl_pwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_pwd)
        self.edt_pwd = QtWidgets.QLineEdit(self.frame)
        self.edt_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.edt_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edt_pwd.setCursorPosition(0)
        self.edt_pwd.setObjectName("edt_pwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edt_pwd)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_SignIn = QtWidgets.QPushButton(self.frame)
        self.btn_SignIn.setObjectName("btn_SignIn")
        self.horizontalLayout_10.addWidget(self.btn_SignIn)
        self.lbl_status = QtWidgets.QLabel(self.frame)
        self.lbl_status.setStyleSheet("background-color: #ffffcc;")
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout_10.addWidget(self.lbl_status)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout.addWidget(self.frame)
        self.line_4 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.frame1 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.grp_project = QtWidgets.QGroupBox(self.frame1)
        self.grp_project.setObjectName("grp_project")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.grp_project)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cmb_project = QtWidgets.QComboBox(self.grp_project)
        self.cmb_project.setObjectName("cmb_project")
        self.verticalLayout_14.addWidget(self.cmb_project)
        self.verticalLayout_6.addWidget(self.grp_project)
        self.splitter_8 = QtWidgets.QSplitter(self.frame1)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_8)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_4.addWidget(self.btn_refresh)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_4.addWidget(self.btn_reset)
        self.verticalLayout_6.addWidget(self.splitter_8)
        self.horizontalLayout.addWidget(self.frame1)
        self.line_6 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.frame2 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_7 = QtWidgets.QSplitter(self.frame2)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.grp_what = QtWidgets.QGroupBox(self.splitter_7)
        self.grp_what.setTitle("")
        self.grp_what.setFlat(True)
        self.grp_what.setObjectName("grp_what")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.grp_what)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rb_sel_download = QtWidgets.QRadioButton(self.grp_what)
        self.rb_sel_download.setObjectName("rb_sel_download")
        self.horizontalLayout_5.addWidget(self.rb_sel_download)
        self.rb_sel_upload = QtWidgets.QRadioButton(self.grp_what)
        self.rb_sel_upload.setObjectName("rb_sel_upload")
        self.horizontalLayout_5.addWidget(self.rb_sel_upload)
        self.grp_download_method = QtWidgets.QGroupBox(self.splitter_7)
        self.grp_download_method.setTitle("")
        self.grp_download_method.setFlat(True)
        self.grp_download_method.setObjectName("grp_download_method")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.grp_download_method)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rb_down_https = QtWidgets.QRadioButton(self.grp_download_method)
        self.rb_down_https.setObjectName("rb_down_https")
        self.horizontalLayout_3.addWidget(self.rb_down_https)
        self.rb_down_nfs = QtWidgets.QRadioButton(self.grp_download_method)
        self.rb_down_nfs.setObjectName("rb_down_nfs")
        self.horizontalLayout_3.addWidget(self.rb_down_nfs)
        self.verticalLayout_4.addWidget(self.splitter_7)
        self.horizontalLayout.addWidget(self.frame2)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_page1 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page1.setObjectName("btn_page1")
        self.horizontalLayout_2.addWidget(self.btn_page1)
        self.btn_page2 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page2.setObjectName("btn_page2")
        self.horizontalLayout_2.addWidget(self.btn_page2)
        self.btn_page3 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page3.setObjectName("btn_page3")
        self.horizontalLayout_2.addWidget(self.btn_page3)
        self.btn_page4 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page4.setObjectName("btn_page4")
        self.horizontalLayout_2.addWidget(self.btn_page4)
        self.btn_page5 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page5.setObjectName("btn_page5")
        self.horizontalLayout_2.addWidget(self.btn_page5)
        self.btn_page6 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page6.setObjectName("btn_page6")
        self.horizontalLayout_2.addWidget(self.btn_page6)
        self.btn_sysconfig = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sysconfig.sizePolicy().hasHeightForWidth())
        self.btn_sysconfig.setSizePolicy(sizePolicy)
        self.btn_sysconfig.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_sysconfig.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_sysconfig.setObjectName("btn_sysconfig")
        self.horizontalLayout_2.addWidget(self.btn_sysconfig)
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.page_1)
        self.splitter_2.setToolTipDuration(-1)
        self.splitter_2.setLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_sub_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_sub_2.setObjectName("lbl_sub_2")
        self.verticalLayout_7.addWidget(self.lbl_sub_2)
        self.edt_search_subj = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edt_search_subj.setObjectName("edt_search_subj")
        self.verticalLayout_7.addWidget(self.edt_search_subj)
        self.lst_subjects = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.lst_subjects.setObjectName("lst_subjects")
        self.verticalLayout_7.addWidget(self.lst_subjects)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_sess_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_sess_2.setObjectName("lbl_sess_2")
        self.verticalLayout_8.addWidget(self.lbl_sess_2)
        self.edt_search_sess = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edt_search_sess.setObjectName("edt_search_sess")
        self.verticalLayout_8.addWidget(self.edt_search_sess)
        self.tree_sessions = QtWidgets.QTreeWidget(self.verticalLayoutWidget_3)
        self.tree_sessions.setObjectName("tree_sessions")
        self.tree_sessions.headerItem().setText(0, "1")
        self.verticalLayout_8.addWidget(self.tree_sessions)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_scan_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lbl_scan_2.setObjectName("lbl_scan_2")
        self.verticalLayout_9.addWidget(self.lbl_scan_2)
        self.grp_scan_quality = QtWidgets.QGroupBox(self.verticalLayoutWidget_4)
        self.grp_scan_quality.setObjectName("grp_scan_quality")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.grp_scan_quality)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.chk_quality_1 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_1.setObjectName("chk_quality_1")
        self.horizontalLayout_16.addWidget(self.chk_quality_1)
        self.chk_quality_2 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_2.setObjectName("chk_quality_2")
        self.horizontalLayout_16.addWidget(self.chk_quality_2)
        self.chk_quality_3 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_3.setObjectName("chk_quality_3")
        self.horizontalLayout_16.addWidget(self.chk_quality_3)
        self.chk_quality_4 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_4.setObjectName("chk_quality_4")
        self.horizontalLayout_16.addWidget(self.chk_quality_4)
        self.chk_quality_5 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_5.setObjectName("chk_quality_5")
        self.horizontalLayout_16.addWidget(self.chk_quality_5)
        self.chk_quality_6 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_6.setObjectName("chk_quality_6")
        self.horizontalLayout_16.addWidget(self.chk_quality_6)
        self.verticalLayout_9.addWidget(self.grp_scan_quality)
        self.tree_scans = QtWidgets.QTreeWidget(self.verticalLayoutWidget_4)
        self.tree_scans.setObjectName("tree_scans")
        self.tree_scans.headerItem().setText(0, "1")
        self.verticalLayout_9.addWidget(self.tree_scans)
        self.horizontalLayout_7.addWidget(self.splitter_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.splitter_3 = QtWidgets.QSplitter(self.page_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.grp_send = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send.sizePolicy().hasHeightForWidth())
        self.grp_send.setSizePolicy(sizePolicy)
        self.grp_send.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_send.setTitle("")
        self.grp_send.setObjectName("grp_send")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.grp_send)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edt_path_txt = QtWidgets.QLineEdit(self.grp_send)
        self.edt_path_txt.setObjectName("edt_path_txt")
        self.gridLayout_3.addWidget(self.edt_path_txt, 0, 0, 1, 1)
        self.btn_send_edt = QtWidgets.QPushButton(self.grp_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_edt.sizePolicy().hasHeightForWidth())
        self.btn_send_edt.setSizePolicy(sizePolicy)
        self.btn_send_edt.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_edt.setObjectName("btn_send_edt")
        self.gridLayout_3.addWidget(self.btn_send_edt, 0, 1, 1, 1)
        self.cmb_path_txt = QtWidgets.QComboBox(self.grp_send)
        self.cmb_path_txt.setObjectName("cmb_path_txt")
        self.gridLayout_3.addWidget(self.cmb_path_txt, 1, 0, 1, 1)
        self.btn_send_cmb = QtWidgets.QPushButton(self.grp_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_cmb.sizePolicy().hasHeightForWidth())
        self.btn_send_cmb.setSizePolicy(sizePolicy)
        self.btn_send_cmb.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_cmb.setObjectName("btn_send_cmb")
        self.gridLayout_3.addWidget(self.btn_send_cmb, 1, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_3)
        self.gridFrame = QtWidgets.QFrame(self.grp_send)
        self.gridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame.setLineWidth(0)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_reset_path_selected = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_selected.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_selected.setSizePolicy(sizePolicy)
        self.btn_reset_path_selected.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_selected.setObjectName("btn_reset_path_selected")
        self.gridLayout.addWidget(self.btn_reset_path_selected, 0, 0, 1, 1)
        self.btn_reset_path_all = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_all.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_all.setSizePolicy(sizePolicy)
        self.btn_reset_path_all.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_all.setObjectName("btn_reset_path_all")
        self.gridLayout.addWidget(self.btn_reset_path_all, 1, 0, 1, 1)
        self.btn_mk_bids = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mk_bids.sizePolicy().hasHeightForWidth())
        self.btn_mk_bids.setSizePolicy(sizePolicy)
        self.btn_mk_bids.setObjectName("btn_mk_bids")
        self.gridLayout.addWidget(self.btn_mk_bids, 0, 1, 1, 1)
        self.chk_BIDS_extra = QtWidgets.QCheckBox(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_BIDS_extra.sizePolicy().hasHeightForWidth())
        self.chk_BIDS_extra.setSizePolicy(sizePolicy)
        self.chk_BIDS_extra.setObjectName("chk_BIDS_extra")
        self.gridLayout.addWidget(self.chk_BIDS_extra, 1, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.gridFrame)
        self.grp_send_path_loc_2 = QtWidgets.QGroupBox(self.splitter_3)
        self.grp_send_path_loc_2.setTitle("")
        self.grp_send_path_loc_2.setObjectName("grp_send_path_loc_2")
        self.layout_path_outer = QtWidgets.QVBoxLayout(self.grp_send_path_loc_2)
        self.layout_path_outer.setContentsMargins(0, 0, 0, 0)
        self.layout_path_outer.setSpacing(6)
        self.layout_path_outer.setObjectName("layout_path_outer")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.chk_path_select_all_path = QtWidgets.QCheckBox(self.grp_send_path_loc_2)
        self.chk_path_select_all_path.setObjectName("chk_path_select_all_path")
        self.horizontalLayout_11.addWidget(self.chk_path_select_all_path)
        self.chk_path_select_all_filename = QtWidgets.QCheckBox(self.grp_send_path_loc_2)
        self.chk_path_select_all_filename.setObjectName("chk_path_select_all_filename")
        self.horizontalLayout_11.addWidget(self.chk_path_select_all_filename)
        self.layout_path_outer.addLayout(self.horizontalLayout_11)
        self.grp_send_path_loc = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send_path_loc.sizePolicy().hasHeightForWidth())
        self.grp_send_path_loc.setSizePolicy(sizePolicy)
        self.grp_send_path_loc.setTitle("")
        self.grp_send_path_loc.setObjectName("grp_send_path_loc")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.grp_send_path_loc)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rb_send_path = QtWidgets.QRadioButton(self.grp_send_path_loc)
        self.rb_send_path.setObjectName("rb_send_path")
        self.horizontalLayout_8.addWidget(self.rb_send_path)
        self.rb_send_file = QtWidgets.QRadioButton(self.grp_send_path_loc)
        self.rb_send_file.setObjectName("rb_send_file")
        self.horizontalLayout_8.addWidget(self.rb_send_file)
        self.verticalLayout_10.addWidget(self.splitter_3)
        self.grp_path = QtWidgets.QGroupBox(self.page_2)
        self.grp_path.setObjectName("grp_path")
        self.verticalLayout_10.addWidget(self.grp_path)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_6 = QtWidgets.QSplitter(self.page_3)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.lst_sel_log = QtWidgets.QListWidget(self.splitter_4)
        self.lst_sel_log.setObjectName("lst_sel_log")
        self.lst_dest_pick = QtWidgets.QListWidget(self.splitter_4)
        self.lst_dest_pick.setObjectName("lst_dest_pick")
        self.lst_filename = QtWidgets.QListWidget(self.splitter_4)
        self.lst_filename.setObjectName("lst_filename")
        self.lst_cmd = QtWidgets.QListWidget(self.splitter_4)
        self.lst_cmd.setObjectName("lst_cmd")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rb_dcm = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_dcm.setObjectName("rb_dcm")
        self.gridLayout_2.addWidget(self.rb_dcm, 0, 0, 1, 1)
        self.rb_afni = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_afni.setObjectName("rb_afni")
        self.gridLayout_2.addWidget(self.rb_afni, 1, 0, 1, 1)
        self.rb_nifti = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_nifti.setObjectName("rb_nifti")
        self.gridLayout_2.addWidget(self.rb_nifti, 0, 1, 1, 1)
        self.rb_custom = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_custom.setObjectName("rb_custom")
        self.gridLayout_2.addWidget(self.rb_custom, 1, 1, 1, 1)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.edt_down_status = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edt_down_status.setFont(font)
        self.edt_down_status.setObjectName("edt_down_status")
        self.verticalLayout_13.addWidget(self.edt_down_status)
        self.edt_down_cmd = QtWidgets.QLineEdit(self.groupBox)
        self.edt_down_cmd.setObjectName("edt_down_cmd")
        self.verticalLayout_13.addWidget(self.edt_down_cmd)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_refresh_cmd = QtWidgets.QPushButton(self.groupBox)
        self.btn_refresh_cmd.setObjectName("btn_refresh_cmd")
        self.verticalLayout_12.addWidget(self.btn_refresh_cmd)
        self.btn_download = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download.setFont(font)
        self.btn_download.setAutoFillBackground(False)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout_12.addWidget(self.btn_download)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.splitter_6)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.splitter_5 = QtWidgets.QSplitter(self.page_4)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.tree_upload_main = QtWidgets.QTreeWidget(self.splitter_5)
        self.tree_upload_main.setObjectName("tree_upload_main")
        self.tree_upload_main.headerItem().setText(0, "1")
        self.layoutWidget_5 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rb_up_res_existing = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rb_up_res_existing.setObjectName("rb_up_res_existing")
        self.verticalLayout_15.addWidget(self.rb_up_res_existing)
        self.cmb_up_res = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_up_res.setObjectName("cmb_up_res")
        self.verticalLayout_15.addWidget(self.cmb_up_res)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.rb_up_res_new = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rb_up_res_new.setObjectName("rb_up_res_new")
        self.verticalLayout_16.addWidget(self.rb_up_res_new)
        self.edt_up_res = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.edt_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_up_res.setObjectName("edt_up_res")
        self.verticalLayout_16.addWidget(self.edt_up_res)
        self.btn_up_res = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_up_res.setObjectName("btn_up_res")
        self.verticalLayout_16.addWidget(self.btn_up_res)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.btn_upload = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_upload.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upload.setFont(font)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout_15.addWidget(self.btn_upload)
        self.horizontalLayout_17.addWidget(self.splitter_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.splitter_9 = QtWidgets.QSplitter(self.page_5)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.tableView = QtWidgets.QTableView(self.splitter_9)
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter_9)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_export_csv = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_export_csv.setObjectName("btn_export_csv")
        self.horizontalLayout_6.addWidget(self.btn_export_csv)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btn_export_xlsx = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_export_xlsx.setObjectName("btn_export_xlsx")
        self.horizontalLayout_6.addWidget(self.btn_export_xlsx)
        self.verticalLayout_17.addWidget(self.splitter_9)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_logger = QtWidgets.QTabWidget(self.verticalFrame)
        self.tab_logger.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.tab_logger.setObjectName("tab_logger")
        self.tab_progress = QtWidgets.QWidget()
        self.tab_progress.setObjectName("tab_progress")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_progress)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pb_final = QtWidgets.QProgressBar(self.tab_progress)
        self.pb_final.setProperty("value", 24)
        self.pb_final.setObjectName("pb_final")
        self.verticalLayout_18.addWidget(self.pb_final)
        self.pb_inter = QtWidgets.QProgressBar(self.tab_progress)
        self.pb_inter.setProperty("value", 24)
        self.pb_inter.setObjectName("pb_inter")
        self.verticalLayout_18.addWidget(self.pb_inter)
        self.pb_inter.raise_()
        self.pb_final.raise_()
        self.pb_final.raise_()
        self.tab_logger.addTab(self.tab_progress, "")
        self.tab_short = QtWidgets.QWidget()
        self.tab_short.setObjectName("tab_short")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_short)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txt_browser_short = QtWidgets.QTextBrowser(self.tab_short)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_browser_short.sizePolicy().hasHeightForWidth())
        self.txt_browser_short.setSizePolicy(sizePolicy)
        self.txt_browser_short.setObjectName("txt_browser_short")
        self.verticalLayout_3.addWidget(self.txt_browser_short)
        self.tab_logger.addTab(self.tab_short, "")
        self.tab_detailed = QtWidgets.QWidget()
        self.tab_detailed.setObjectName("tab_detailed")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_detailed)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_browser_detailed = QtWidgets.QTextBrowser(self.tab_detailed)
        self.txt_browser_detailed.setObjectName("txt_browser_detailed")
        self.verticalLayout_5.addWidget(self.txt_browser_detailed)
        self.tab_logger.addTab(self.tab_detailed, "")
        self.verticalLayout.addWidget(self.tab_logger)
        self.verticalLayout_11.addWidget(self.splitter)
        XnatDUI.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(XnatDUI)
        self.mainToolBar.setObjectName("mainToolBar")
        XnatDUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(XnatDUI)
        self.statusBar.setObjectName("statusBar")
        XnatDUI.setStatusBar(self.statusBar)

        self.retranslateUi(XnatDUI)
        self.stackedWidget.setCurrentIndex(4)
        self.tab_logger.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(XnatDUI)

    def retranslateUi(self, XnatDUI):
        _translate = QtCore.QCoreApplication.translate
        XnatDUI.setWindowTitle(_translate("XnatDUI", "Xnat Download Upload Interface v1.0"))
        self.lbl_host.setText(_translate("XnatDUI", "Host:"))
        self.edt_host.setPlaceholderText(_translate("XnatDUI", "http://<XNAT-HOSTNAME> or https://<XNAT-HOSTNAME>"))
        self.lbl_username.setText(_translate("XnatDUI", "Username :"))
        self.edt_username.setPlaceholderText(_translate("XnatDUI", "Your XNAT username"))
        self.lbl_pwd.setText(_translate("XnatDUI", "Password :"))
        self.edt_pwd.setPlaceholderText(_translate("XnatDUI", "ENTER PASSWORD"))
        self.btn_SignIn.setText(_translate("XnatDUI", "Sign In"))
        self.grp_project.setTitle(_translate("XnatDUI", "Select Project"))
        self.btn_refresh.setText(_translate("XnatDUI", "Refresh Conn"))
        self.btn_reset.setText(_translate("XnatDUI", "Reset All"))
        self.rb_sel_download.setText(_translate("XnatDUI", "Download"))
        self.rb_sel_upload.setText(_translate("XnatDUI", "Upload"))
        self.rb_down_https.setText(_translate("XnatDUI", "via HTTPS"))
        self.rb_down_nfs.setText(_translate("XnatDUI", "via NFS"))
        self.btn_page1.setText(_translate("XnatDUI", "Select"))
        self.btn_page2.setText(_translate("XnatDUI", "Destination"))
        self.btn_page3.setText(_translate("XnatDUI", "Download"))
        self.btn_page4.setText(_translate("XnatDUI", "Upload"))
        self.btn_page5.setText(_translate("XnatDUI", "Export Selection"))
        self.btn_page6.setText(_translate("XnatDUI", "Run Process"))
        self.btn_sysconfig.setText(_translate("XnatDUI", "..."))
        self.lbl_sub_2.setText(_translate("XnatDUI", "Select Subjects"))
        self.edt_search_subj.setPlaceholderText(_translate("XnatDUI", "Search SUBJECT label"))
        self.lbl_sess_2.setText(_translate("XnatDUI", "Select Sessions"))
        self.edt_search_sess.setPlaceholderText(_translate("XnatDUI", "Search SESSION Label"))
        self.lbl_scan_2.setText(_translate("XnatDUI", "Select Scans"))
        self.chk_quality_1.setText(_translate("XnatDUI", "Qlty1"))
        self.chk_quality_2.setText(_translate("XnatDUI", "Qlty2"))
        self.chk_quality_3.setText(_translate("XnatDUI", "Qlty3"))
        self.chk_quality_4.setText(_translate("XnatDUI", "Qlty4"))
        self.chk_quality_5.setText(_translate("XnatDUI", "Qlty5"))
        self.chk_quality_6.setText(_translate("XnatDUI", "Qlty6"))
        self.edt_path_txt.setPlaceholderText(_translate("XnatDUI", "Enter text to Send"))
        self.btn_send_edt.setText(_translate("XnatDUI", "Send"))
        self.btn_send_cmb.setText(_translate("XnatDUI", "Send"))
        self.btn_reset_path_selected.setText(_translate("XnatDUI", "Reset Selected"))
        self.btn_reset_path_all.setText(_translate("XnatDUI", "Reeset All"))
        self.btn_mk_bids.setText(_translate("XnatDUI", "Make BIDS Paths"))
        self.chk_BIDS_extra.setText(_translate("XnatDUI", "Download BIDS"))
        self.chk_path_select_all_path.setText(_translate("XnatDUI", "Check/Uncheck All PATHs"))
        self.chk_path_select_all_filename.setText(_translate("XnatDUI", "Check/Uncheck All Filenames"))
        self.rb_send_path.setText(_translate("XnatDUI", "Send to PATH name"))
        self.rb_send_file.setText(_translate("XnatDUI", "Send to FILE name"))
        self.grp_path.setTitle(_translate("XnatDUI", "Create Unique Paths"))
        self.groupBox_2.setTitle(_translate("XnatDUI", "Select Format"))
        self.rb_dcm.setText(_translate("XnatDUI", "DICOM"))
        self.rb_afni.setText(_translate("XnatDUI", "AFNI"))
        self.rb_nifti.setText(_translate("XnatDUI", "NIFTI"))
        self.rb_custom.setText(_translate("XnatDUI", "Custom"))
        self.groupBox.setTitle(_translate("XnatDUI", "Conversion Script"))
        self.edt_down_status.setText(_translate("XnatDUI", "Status: Ready"))
        self.btn_refresh_cmd.setText(_translate("XnatDUI", "Refresh"))
        self.btn_download.setText(_translate("XnatDUI", "   DOWNLOAD  "))
        self.rb_up_res_existing.setText(_translate("XnatDUI", "Select Existing Type"))
        self.rb_up_res_new.setText(_translate("XnatDUI", "Create New Type"))
        self.edt_up_res.setPlaceholderText(_translate("XnatDUI", "Enter new RESOURCE Name"))
        self.btn_up_res.setText(_translate("XnatDUI", "Create New Resource"))
        self.btn_upload.setText(_translate("XnatDUI", "UPLOAD"))
        self.btn_export_csv.setText(_translate("XnatDUI", "Export to CSV"))
        self.btn_export_xlsx.setText(_translate("XnatDUI", "Export to XLSX"))
        self.tab_logger.setTabText(self.tab_logger.indexOf(self.tab_progress), _translate("XnatDUI", "Page"))
        self.tab_logger.setTabText(self.tab_logger.indexOf(self.tab_short), _translate("XnatDUI", "Short Logger"))
        self.tab_logger.setTabText(self.tab_logger.indexOf(self.tab_detailed), _translate("XnatDUI", "Detailed Logger"))

