# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xnatdui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XnatDUI(object):
    def setupUi(self, XnatDUI):
        XnatDUI.setObjectName("XnatDUI")
        XnatDUI.resize(790, 786)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(XnatDUI.sizePolicy().hasHeightForWidth())
        XnatDUI.setSizePolicy(sizePolicy)
        XnatDUI.setMinimumSize(QtCore.QSize(780, 576))
        XnatDUI.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralWidget = QtWidgets.QWidget(XnatDUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_main.setContentsMargins(2, 2, 2, 1)
        self.verticalLayout_main.setSpacing(1)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(2, 0, 0, 0)
        self.formLayout.setSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.lbl_host = QtWidgets.QLabel(self.frame)
        self.lbl_host.setObjectName("lbl_host")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_host)
        self.edt_host = QtWidgets.QLineEdit(self.frame)
        self.edt_host.setObjectName("edt_host")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edt_host)
        self.lbl_username = QtWidgets.QLabel(self.frame)
        self.lbl_username.setObjectName("lbl_username")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_username)
        self.edt_username = QtWidgets.QLineEdit(self.frame)
        self.edt_username.setObjectName("edt_username")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edt_username)
        self.lbl_pwd = QtWidgets.QLabel(self.frame)
        self.lbl_pwd.setObjectName("lbl_pwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_pwd)
        self.edt_pwd = QtWidgets.QLineEdit(self.frame)
        self.edt_pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.edt_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edt_pwd.setCursorPosition(0)
        self.edt_pwd.setObjectName("edt_pwd")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edt_pwd)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_SignIn = QtWidgets.QPushButton(self.frame)
        self.btn_SignIn.setObjectName("btn_SignIn")
        self.horizontalLayout_10.addWidget(self.btn_SignIn)
        self.lbl_status = QtWidgets.QLabel(self.frame)
        self.lbl_status.setStyleSheet("background-color: #ffffcc;")
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout_10.addWidget(self.lbl_status)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.horizontalLayout.addWidget(self.frame)
        self.line_4 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.frame1 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.grp_project = QtWidgets.QGroupBox(self.frame1)
        self.grp_project.setObjectName("grp_project")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.grp_project)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cmb_project = QtWidgets.QComboBox(self.grp_project)
        self.cmb_project.setObjectName("cmb_project")
        self.verticalLayout_14.addWidget(self.cmb_project)
        self.verticalLayout_6.addWidget(self.grp_project)
        self.splitter_8 = QtWidgets.QSplitter(self.frame1)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_8)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 2, 1)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_4.addWidget(self.btn_refresh)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_4.addWidget(self.btn_reset)
        self.verticalLayout_6.addWidget(self.splitter_8)
        self.horizontalLayout.addWidget(self.frame1)
        self.line_6 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.frame2 = QtWidgets.QFrame(self.horizontalGroupBox)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_4.setContentsMargins(1, 1, 2, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_7 = QtWidgets.QSplitter(self.frame2)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.grp_what = QtWidgets.QGroupBox(self.splitter_7)
        self.grp_what.setTitle("")
        self.grp_what.setFlat(True)
        self.grp_what.setObjectName("grp_what")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.grp_what)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rb_sel_download = QtWidgets.QRadioButton(self.grp_what)
        self.rb_sel_download.setObjectName("rb_sel_download")
        self.horizontalLayout_5.addWidget(self.rb_sel_download)
        self.rb_sel_upload = QtWidgets.QRadioButton(self.grp_what)
        self.rb_sel_upload.setObjectName("rb_sel_upload")
        self.horizontalLayout_5.addWidget(self.rb_sel_upload)
        self.grp_logging_info = QtWidgets.QGroupBox(self.splitter_7)
        self.grp_logging_info.setTitle("")
        self.grp_logging_info.setFlat(True)
        self.grp_logging_info.setObjectName("grp_logging_info")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.grp_logging_info)
        self.verticalLayout_23.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.chk_export = QtWidgets.QCheckBox(self.grp_logging_info)
        self.chk_export.setObjectName("chk_export")
        self.verticalLayout_23.addWidget(self.chk_export)
        self.line = QtWidgets.QFrame(self.grp_logging_info)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_23.addWidget(self.line)
        self.btn_view_logs = QtWidgets.QPushButton(self.grp_logging_info)
        self.btn_view_logs.setObjectName("btn_view_logs")
        self.verticalLayout_23.addWidget(self.btn_view_logs)
        self.rb_logs_short = QtWidgets.QRadioButton(self.grp_logging_info)
        self.rb_logs_short.setObjectName("rb_logs_short")
        self.verticalLayout_23.addWidget(self.rb_logs_short)
        self.rb_logs_detailed = QtWidgets.QRadioButton(self.grp_logging_info)
        self.rb_logs_detailed.setObjectName("rb_logs_detailed")
        self.verticalLayout_23.addWidget(self.rb_logs_detailed)
        self.verticalLayout_4.addWidget(self.splitter_7)
        self.horizontalLayout.addWidget(self.frame2)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_page1 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page1.setObjectName("btn_page1")
        self.horizontalLayout_2.addWidget(self.btn_page1)
        self.btn_page1B = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page1B.setObjectName("btn_page1B")
        self.horizontalLayout_2.addWidget(self.btn_page1B)
        self.btn_page2 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page2.setObjectName("btn_page2")
        self.horizontalLayout_2.addWidget(self.btn_page2)
        self.btn_page3 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page3.setObjectName("btn_page3")
        self.horizontalLayout_2.addWidget(self.btn_page3)
        self.btn_page4 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page4.setObjectName("btn_page4")
        self.horizontalLayout_2.addWidget(self.btn_page4)
        self.btn_page5 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page5.setObjectName("btn_page5")
        self.horizontalLayout_2.addWidget(self.btn_page5)
        self.btn_page6 = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        self.btn_page6.setObjectName("btn_page6")
        self.horizontalLayout_2.addWidget(self.btn_page6)
        self.btn_sysconfig = QtWidgets.QPushButton(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sysconfig.sizePolicy().hasHeightForWidth())
        self.btn_sysconfig.setSizePolicy(sizePolicy)
        self.btn_sysconfig.setMinimumSize(QtCore.QSize(20, 0))
        self.btn_sysconfig.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btn_sysconfig.setObjectName("btn_sysconfig")
        self.horizontalLayout_2.addWidget(self.btn_sysconfig)
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.page_1)
        self.splitter_2.setToolTipDuration(-1)
        self.splitter_2.setLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setObjectName("splitter_2")
        self.vf_subjects = QtWidgets.QFrame(self.splitter_2)
        self.vf_subjects.setObjectName("vf_subjects")
        self.vl_subjects = QtWidgets.QVBoxLayout(self.vf_subjects)
        self.vl_subjects.setContentsMargins(0, 0, 0, 0)
        self.vl_subjects.setSpacing(0)
        self.vl_subjects.setObjectName("vl_subjects")
        self.lbl_sub = QtWidgets.QLabel(self.vf_subjects)
        self.lbl_sub.setObjectName("lbl_sub")
        self.vl_subjects.addWidget(self.lbl_sub)
        self.grp_subj_select = QtWidgets.QGroupBox(self.vf_subjects)
        self.grp_subj_select.setTitle("")
        self.grp_subj_select.setObjectName("grp_subj_select")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.grp_subj_select)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.rb_subj_sess = QtWidgets.QRadioButton(self.grp_subj_select)
        self.rb_subj_sess.setObjectName("rb_subj_sess")
        self.horizontalLayout_15.addWidget(self.rb_subj_sess)
        self.rb_subj_res = QtWidgets.QRadioButton(self.grp_subj_select)
        self.rb_subj_res.setObjectName("rb_subj_res")
        self.horizontalLayout_15.addWidget(self.rb_subj_res)
        self.vl_subjects.addWidget(self.grp_subj_select)
        self.edt_search_subj = QtWidgets.QLineEdit(self.vf_subjects)
        self.edt_search_subj.setObjectName("edt_search_subj")
        self.vl_subjects.addWidget(self.edt_search_subj)
        self.lst_subjects = QtWidgets.QListWidget(self.vf_subjects)
        self.lst_subjects.setObjectName("lst_subjects")
        self.vl_subjects.addWidget(self.lst_subjects)
        self.vf_sessions = QtWidgets.QFrame(self.splitter_2)
        self.vf_sessions.setObjectName("vf_sessions")
        self.vl_sessions = QtWidgets.QVBoxLayout(self.vf_sessions)
        self.vl_sessions.setContentsMargins(0, 0, 0, 0)
        self.vl_sessions.setSpacing(0)
        self.vl_sessions.setObjectName("vl_sessions")
        self.lbl_sess = QtWidgets.QLabel(self.vf_sessions)
        self.lbl_sess.setObjectName("lbl_sess")
        self.vl_sessions.addWidget(self.lbl_sess)
        self.grp_sess_select = QtWidgets.QGroupBox(self.vf_sessions)
        self.grp_sess_select.setTitle("")
        self.grp_sess_select.setObjectName("grp_sess_select")
        self.horizontalLayout_0 = QtWidgets.QHBoxLayout(self.grp_sess_select)
        self.horizontalLayout_0.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_0.setSpacing(0)
        self.horizontalLayout_0.setObjectName("horizontalLayout_0")
        self.rb_sess_scans = QtWidgets.QRadioButton(self.grp_sess_select)
        self.rb_sess_scans.setObjectName("rb_sess_scans")
        self.horizontalLayout_0.addWidget(self.rb_sess_scans)
        self.rb_sess_res = QtWidgets.QRadioButton(self.grp_sess_select)
        self.rb_sess_res.setObjectName("rb_sess_res")
        self.horizontalLayout_0.addWidget(self.rb_sess_res)
        self.vl_sessions.addWidget(self.grp_sess_select)
        self.edt_search_sess = QtWidgets.QLineEdit(self.vf_sessions)
        self.edt_search_sess.setObjectName("edt_search_sess")
        self.vl_sessions.addWidget(self.edt_search_sess)
        self.tree_sessions = QtWidgets.QTreeWidget(self.vf_sessions)
        self.tree_sessions.setObjectName("tree_sessions")
        self.tree_sessions.headerItem().setText(0, "1")
        self.vl_sessions.addWidget(self.tree_sessions)
        self.vf_scans = QtWidgets.QFrame(self.splitter_2)
        self.vf_scans.setObjectName("vf_scans")
        self.vl_scans = QtWidgets.QVBoxLayout(self.vf_scans)
        self.vl_scans.setContentsMargins(0, 0, 0, 0)
        self.vl_scans.setSpacing(0)
        self.vl_scans.setObjectName("vl_scans")
        self.lbl_scan = QtWidgets.QLabel(self.vf_scans)
        self.lbl_scan.setObjectName("lbl_scan")
        self.vl_scans.addWidget(self.lbl_scan)
        self.grp_scan_quality = QtWidgets.QGroupBox(self.vf_scans)
        self.grp_scan_quality.setObjectName("grp_scan_quality")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.grp_scan_quality)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.chk_quality_1 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_1.setObjectName("chk_quality_1")
        self.horizontalLayout_16.addWidget(self.chk_quality_1)
        self.chk_quality_2 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_2.setObjectName("chk_quality_2")
        self.horizontalLayout_16.addWidget(self.chk_quality_2)
        self.chk_quality_3 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_3.setObjectName("chk_quality_3")
        self.horizontalLayout_16.addWidget(self.chk_quality_3)
        self.chk_quality_4 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_4.setObjectName("chk_quality_4")
        self.horizontalLayout_16.addWidget(self.chk_quality_4)
        self.chk_quality_5 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_5.setObjectName("chk_quality_5")
        self.horizontalLayout_16.addWidget(self.chk_quality_5)
        self.chk_quality_6 = QtWidgets.QCheckBox(self.grp_scan_quality)
        self.chk_quality_6.setObjectName("chk_quality_6")
        self.horizontalLayout_16.addWidget(self.chk_quality_6)
        self.vl_scans.addWidget(self.grp_scan_quality)
        self.lbl_resources = QtWidgets.QLabel(self.vf_scans)
        self.lbl_resources.setObjectName("lbl_resources")
        self.vl_scans.addWidget(self.lbl_resources)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.chk_res_1 = QtWidgets.QCheckBox(self.vf_scans)
        self.chk_res_1.setObjectName("chk_res_1")
        self.horizontalLayout_13.addWidget(self.chk_res_1)
        self.chk_res_2 = QtWidgets.QCheckBox(self.vf_scans)
        self.chk_res_2.setObjectName("chk_res_2")
        self.horizontalLayout_13.addWidget(self.chk_res_2)
        self.chk_res_3 = QtWidgets.QCheckBox(self.vf_scans)
        self.chk_res_3.setObjectName("chk_res_3")
        self.horizontalLayout_13.addWidget(self.chk_res_3)
        self.chk_res_4 = QtWidgets.QCheckBox(self.vf_scans)
        self.chk_res_4.setObjectName("chk_res_4")
        self.horizontalLayout_13.addWidget(self.chk_res_4)
        self.chk_res_5 = QtWidgets.QCheckBox(self.vf_scans)
        self.chk_res_5.setObjectName("chk_res_5")
        self.horizontalLayout_13.addWidget(self.chk_res_5)
        self.vl_scans.addLayout(self.horizontalLayout_13)
        self.tree_scans = QtWidgets.QTreeWidget(self.vf_scans)
        self.tree_scans.setObjectName("tree_scans")
        self.tree_scans.headerItem().setText(0, "1")
        self.vl_scans.addWidget(self.tree_scans)
        self.horizontalLayout_7.addWidget(self.splitter_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.splitter_3 = QtWidgets.QSplitter(self.page_2)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.grp_send = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send.sizePolicy().hasHeightForWidth())
        self.grp_send.setSizePolicy(sizePolicy)
        self.grp_send.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_send.setTitle("")
        self.grp_send.setObjectName("grp_send")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.grp_send)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(2, 0, 2, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edt_path_txt = QtWidgets.QLineEdit(self.grp_send)
        self.edt_path_txt.setObjectName("edt_path_txt")
        self.gridLayout_3.addWidget(self.edt_path_txt, 0, 0, 1, 1)
        self.btn_send_edt = QtWidgets.QPushButton(self.grp_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_edt.sizePolicy().hasHeightForWidth())
        self.btn_send_edt.setSizePolicy(sizePolicy)
        self.btn_send_edt.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_edt.setObjectName("btn_send_edt")
        self.gridLayout_3.addWidget(self.btn_send_edt, 0, 1, 1, 1)
        self.cmb_path_txt = QtWidgets.QComboBox(self.grp_send)
        self.cmb_path_txt.setObjectName("cmb_path_txt")
        self.gridLayout_3.addWidget(self.cmb_path_txt, 1, 0, 1, 1)
        self.btn_send_cmb = QtWidgets.QPushButton(self.grp_send)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send_cmb.sizePolicy().hasHeightForWidth())
        self.btn_send_cmb.setSizePolicy(sizePolicy)
        self.btn_send_cmb.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_send_cmb.setObjectName("btn_send_cmb")
        self.gridLayout_3.addWidget(self.btn_send_cmb, 1, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_3)
        self.gridFrame = QtWidgets.QFrame(self.grp_send)
        self.gridFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.gridFrame.setLineWidth(0)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setContentsMargins(2, 0, 2, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_reset_path_all = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_all.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_all.setSizePolicy(sizePolicy)
        self.btn_reset_path_all.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_all.setObjectName("btn_reset_path_all")
        self.gridLayout.addWidget(self.btn_reset_path_all, 0, 1, 1, 1)
        self.btn_reset_path_selected = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset_path_selected.sizePolicy().hasHeightForWidth())
        self.btn_reset_path_selected.setSizePolicy(sizePolicy)
        self.btn_reset_path_selected.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_reset_path_selected.setObjectName("btn_reset_path_selected")
        self.gridLayout.addWidget(self.btn_reset_path_selected, 0, 0, 1, 1)
        self.chk_path_all_scans = QtWidgets.QCheckBox(self.gridFrame)
        self.chk_path_all_scans.setObjectName("chk_path_all_scans")
        self.gridLayout.addWidget(self.chk_path_all_scans, 1, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.gridFrame)
        self.grp_send_path_loc = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send_path_loc.sizePolicy().hasHeightForWidth())
        self.grp_send_path_loc.setSizePolicy(sizePolicy)
        self.grp_send_path_loc.setTitle("")
        self.grp_send_path_loc.setObjectName("grp_send_path_loc")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.grp_send_path_loc)
        self.horizontalLayout_8.setContentsMargins(8, 0, 0, 1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rb_send_path = QtWidgets.QRadioButton(self.grp_send_path_loc)
        self.rb_send_path.setObjectName("rb_send_path")
        self.horizontalLayout_8.addWidget(self.rb_send_path)
        self.rb_send_file = QtWidgets.QRadioButton(self.grp_send_path_loc)
        self.rb_send_file.setObjectName("rb_send_file")
        self.horizontalLayout_8.addWidget(self.rb_send_file)
        self.verticalLayout_10.addWidget(self.splitter_3)
        self.grp_path = QtWidgets.QGroupBox(self.page_2)
        self.grp_path.setTitle("")
        self.grp_path.setObjectName("grp_path")
        self.verticalLayout_10.addWidget(self.grp_path)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.splitter_6 = QtWidgets.QSplitter(self.page_3)
        self.splitter_6.setLineWidth(0)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setHandleWidth(1)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(5)
        self.splitter_4.setObjectName("splitter_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lst_sel_log = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lst_sel_log.setAutoScrollMargin(10)
        self.lst_sel_log.setObjectName("lst_sel_log")
        self.verticalLayout_2.addWidget(self.lst_sel_log)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_19.addWidget(self.label_2)
        self.lst_dest_pick = QtWidgets.QListWidget(self.verticalLayoutWidget_5)
        self.lst_dest_pick.setAutoScrollMargin(10)
        self.lst_dest_pick.setObjectName("lst_dest_pick")
        self.verticalLayout_19.addWidget(self.lst_dest_pick)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setIndent(5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_20.addWidget(self.label_3)
        self.lst_filename = QtWidgets.QListWidget(self.verticalLayoutWidget_6)
        self.lst_filename.setAutoScrollMargin(0)
        self.lst_filename.setObjectName("lst_filename")
        self.verticalLayout_20.addWidget(self.lst_filename)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_21.addWidget(self.label_4)
        self.lst_cmd = QtWidgets.QListWidget(self.verticalLayoutWidget_7)
        self.lst_cmd.setAutoScrollMargin(0)
        self.lst_cmd.setObjectName("lst_cmd")
        self.verticalLayout_21.addWidget(self.lst_cmd)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.grp_down_format = QtWidgets.QGroupBox(self.layoutWidget1)
        self.grp_down_format.setObjectName("grp_down_format")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_down_format)
        self.gridLayout_2.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rb_dcm = QtWidgets.QRadioButton(self.grp_down_format)
        self.rb_dcm.setObjectName("rb_dcm")
        self.gridLayout_2.addWidget(self.rb_dcm, 0, 0, 1, 1)
        self.rb_afni = QtWidgets.QRadioButton(self.grp_down_format)
        self.rb_afni.setObjectName("rb_afni")
        self.gridLayout_2.addWidget(self.rb_afni, 1, 0, 1, 1)
        self.rb_nifti = QtWidgets.QRadioButton(self.grp_down_format)
        self.rb_nifti.setObjectName("rb_nifti")
        self.gridLayout_2.addWidget(self.rb_nifti, 0, 1, 1, 1)
        self.rb_custom = QtWidgets.QRadioButton(self.grp_down_format)
        self.rb_custom.setObjectName("rb_custom")
        self.gridLayout_2.addWidget(self.rb_custom, 1, 1, 1, 1)
        self.horizontalLayout_12.addWidget(self.grp_down_format)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.edt_down_status = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edt_down_status.setFont(font)
        self.edt_down_status.setObjectName("edt_down_status")
        self.verticalLayout_13.addWidget(self.edt_down_status)
        self.edt_down_cmd = QtWidgets.QLineEdit(self.groupBox)
        self.edt_down_cmd.setObjectName("edt_down_cmd")
        self.verticalLayout_13.addWidget(self.edt_down_cmd)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_refresh_cmd = QtWidgets.QPushButton(self.groupBox)
        self.btn_refresh_cmd.setObjectName("btn_refresh_cmd")
        self.verticalLayout_12.addWidget(self.btn_refresh_cmd)
        self.btn_download = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download.setFont(font)
        self.btn_download.setAutoFillBackground(False)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout_12.addWidget(self.btn_download)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.verticalLayout_22.addWidget(self.splitter_6)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.splitter_5 = QtWidgets.QSplitter(self.page_4)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.tree_upload_main = QtWidgets.QTreeWidget(self.splitter_5)
        self.tree_upload_main.setObjectName("tree_upload_main")
        self.tree_upload_main.headerItem().setText(0, "1")
        self.layoutWidget_5 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rb_up_res_existing = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rb_up_res_existing.setObjectName("rb_up_res_existing")
        self.verticalLayout_15.addWidget(self.rb_up_res_existing)
        self.cmb_up_res = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_up_res.setObjectName("cmb_up_res")
        self.verticalLayout_15.addWidget(self.cmb_up_res)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.rb_up_res_new = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.rb_up_res_new.setObjectName("rb_up_res_new")
        self.verticalLayout_16.addWidget(self.rb_up_res_new)
        self.edt_up_res = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.edt_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_up_res.setObjectName("edt_up_res")
        self.verticalLayout_16.addWidget(self.edt_up_res)
        self.btn_up_res = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_up_res.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_up_res.setObjectName("btn_up_res")
        self.verticalLayout_16.addWidget(self.btn_up_res)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.btn_upload = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_upload.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upload.setFont(font)
        self.btn_upload.setObjectName("btn_upload")
        self.verticalLayout_15.addWidget(self.btn_upload)
        self.horizontalLayout_17.addWidget(self.splitter_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.splitter_9 = QtWidgets.QSplitter(self.page_5)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.tableView = QtWidgets.QTableView(self.splitter_9)
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter_9)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_export_csv = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_export_csv.setObjectName("btn_export_csv")
        self.horizontalLayout_6.addWidget(self.btn_export_csv)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btn_export_xlsx = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_export_xlsx.setObjectName("btn_export_xlsx")
        self.horizontalLayout_6.addWidget(self.btn_export_xlsx)
        self.verticalLayout_17.addWidget(self.splitter_9)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(6)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.splitter_13 = QtWidgets.QSplitter(self.page_6)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.splitter_12 = QtWidgets.QSplitter(self.splitter_13)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.splitter_12)
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_24.addWidget(self.label_8)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget_8)
        self.listView.setObjectName("listView")
        self.verticalLayout_24.addWidget(self.listView)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.splitter_12)
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_25.addWidget(self.label_9)
        self.listView_2 = QtWidgets.QListView(self.verticalLayoutWidget_9)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_25.addWidget(self.listView_2)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.splitter_12)
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_26.addWidget(self.label_10)
        self.listView_3 = QtWidgets.QListView(self.verticalLayoutWidget_10)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_26.addWidget(self.listView_3)
        self.verticalLayoutWidget_0 = QtWidgets.QWidget(self.splitter_12)
        self.verticalLayoutWidget_0.setObjectName("verticalLayoutWidget_0")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_0)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(6)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_0 = QtWidgets.QLabel(self.verticalLayoutWidget_0)
        self.label_0.setObjectName("label_0")
        self.verticalLayout_27.addWidget(self.label_0)
        self.listView_4 = QtWidgets.QListView(self.verticalLayoutWidget_0)
        self.listView_4.setObjectName("listView_4")
        self.verticalLayout_27.addWidget(self.listView_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_13)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_28.addWidget(self.splitter_13)
        self.stackedWidget.addWidget(self.page_6)
        self.page_1B = QtWidgets.QWidget()
        self.page_1B.setObjectName("page_1B")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.page_1B)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.splitter_14 = QtWidgets.QSplitter(self.page_1B)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.splitter_14)
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.edt_search_subB = QtWidgets.QLineEdit(self.verticalLayoutWidget_12)
        self.edt_search_subB.setObjectName("edt_search_subB")
        self.verticalLayout_3.addWidget(self.edt_search_subB)
        self.lst_subjectsB = QtWidgets.QListWidget(self.verticalLayoutWidget_12)
        self.lst_subjectsB.setObjectName("lst_subjectsB")
        self.verticalLayout_3.addWidget(self.lst_subjectsB)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.splitter_14)
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.edt_search_comp_stat = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.edt_search_comp_stat.setObjectName("edt_search_comp_stat")
        self.verticalLayout_5.addWidget(self.edt_search_comp_stat)
        self.tree_completion_status = QtWidgets.QTreeWidget(self.verticalLayoutWidget_13)
        self.tree_completion_status.setObjectName("tree_completion_status")
        self.tree_completion_status.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.tree_completion_status)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.splitter_14)
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_29.addWidget(self.label_14)
        self.cmb_completion_set = QtWidgets.QComboBox(self.verticalLayoutWidget_14)
        self.cmb_completion_set.setObjectName("cmb_completion_set")
        self.verticalLayout_29.addWidget(self.cmb_completion_set)
        self.tree_scansB = QtWidgets.QTreeWidget(self.verticalLayoutWidget_14)
        self.tree_scansB.setObjectName("tree_scansB")
        self.tree_scansB.headerItem().setText(0, "1")
        self.verticalLayout_29.addWidget(self.tree_scansB)
        self.verticalLayout_30.addWidget(self.splitter_14)
        self.stackedWidget.addWidget(self.page_1B)
        self.page_3B = QtWidgets.QWidget()
        self.page_3B.setObjectName("page_3B")
        self.verticalLayout_0 = QtWidgets.QVBoxLayout(self.page_3B)
        self.verticalLayout_0.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_0.setSpacing(6)
        self.verticalLayout_0.setObjectName("verticalLayout_0")
        self.splitter_0 = QtWidgets.QSplitter(self.page_3B)
        self.splitter_0.setOrientation(QtCore.Qt.Vertical)
        self.splitter_0.setObjectName("splitter_0")
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_0)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_10)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.lst_res_src = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.lst_res_src.setObjectName("lst_res_src")
        self.verticalLayout_7.addWidget(self.lst_res_src)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_10)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.lst_res_outdir = QtWidgets.QListView(self.verticalLayoutWidget_3)
        self.lst_res_outdir.setObjectName("lst_res_outdir")
        self.verticalLayout_8.addWidget(self.lst_res_outdir)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.splitter_10)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.lst_res_fname = QtWidgets.QListView(self.verticalLayoutWidget_4)
        self.lst_res_fname.setObjectName("lst_res_fname")
        self.verticalLayout_9.addWidget(self.lst_res_fname)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_0)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_18.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.btn_res_download = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_res_download.setObjectName("btn_res_download")
        self.horizontalLayout_18.addWidget(self.btn_res_download)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.verticalLayout_0.addWidget(self.splitter_0)
        self.stackedWidget.addWidget(self.page_3B)
        self.verticalFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_logger = QtWidgets.QFrame(self.verticalFrame)
        self.tab_logger.setMaximumSize(QtCore.QSize(16777215, 16777209))
        self.tab_logger.setObjectName("tab_logger")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_logger)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pb_final = QtWidgets.QProgressBar(self.tab_logger)
        self.pb_final.setProperty("value", 0)
        self.pb_final.setObjectName("pb_final")
        self.verticalLayout_18.addWidget(self.pb_final)
        self.pb_inter = QtWidgets.QProgressBar(self.tab_logger)
        self.pb_inter.setProperty("value", 0)
        self.pb_inter.setObjectName("pb_inter")
        self.verticalLayout_18.addWidget(self.pb_inter)
        self.pb_inter.raise_()
        self.pb_final.raise_()
        self.verticalLayout.addWidget(self.tab_logger)
        self.verticalLayout_main.addWidget(self.splitter)
        XnatDUI.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(XnatDUI)
        self.mainToolBar.setObjectName("mainToolBar")
        XnatDUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(XnatDUI)
        self.statusBar.setObjectName("statusBar")
        XnatDUI.setStatusBar(self.statusBar)

        self.retranslateUi(XnatDUI)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(XnatDUI)

    def retranslateUi(self, XnatDUI):
        _translate = QtCore.QCoreApplication.translate
        XnatDUI.setWindowTitle(_translate("XnatDUI", "Xnat Download Upload Interface v1.0"))
        self.lbl_host.setText(_translate("XnatDUI", "Host:"))
        self.edt_host.setPlaceholderText(_translate("XnatDUI", "http://<XNAT-HOSTNAME> or https://<XNAT-HOSTNAME>"))
        self.lbl_username.setText(_translate("XnatDUI", "Username :"))
        self.edt_username.setPlaceholderText(_translate("XnatDUI", "Your XNAT username"))
        self.lbl_pwd.setText(_translate("XnatDUI", "Password :"))
        self.edt_pwd.setPlaceholderText(_translate("XnatDUI", "ENTER PASSWORD"))
        self.btn_SignIn.setText(_translate("XnatDUI", "Sign In"))
        self.grp_project.setTitle(_translate("XnatDUI", "Select Project"))
        self.btn_refresh.setText(_translate("XnatDUI", "Refresh Conn"))
        self.btn_reset.setText(_translate("XnatDUI", "Reset All"))
        self.rb_sel_download.setText(_translate("XnatDUI", "Download"))
        self.rb_sel_upload.setText(_translate("XnatDUI", "Upload"))
        self.chk_export.setText(_translate("XnatDUI", "Export Only"))
        self.btn_view_logs.setText(_translate("XnatDUI", "View Historic Logs"))
        self.rb_logs_short.setText(_translate("XnatDUI", "Save Short Log"))
        self.rb_logs_detailed.setText(_translate("XnatDUI", "Save Detailed Log"))
        self.btn_page1.setText(_translate("XnatDUI", "Select"))
        self.btn_page1B.setText(_translate("XnatDUI", "Completion Status"))
        self.btn_page2.setText(_translate("XnatDUI", "Destination"))
        self.btn_page3.setText(_translate("XnatDUI", "Download"))
        self.btn_page4.setText(_translate("XnatDUI", "Upload"))
        self.btn_page5.setText(_translate("XnatDUI", "Export Selection"))
        self.btn_page6.setText(_translate("XnatDUI", "Run Process"))
        self.btn_sysconfig.setText(_translate("XnatDUI", "..."))
        self.lbl_sub.setText(_translate("XnatDUI", "Select Subjects"))
        self.rb_subj_sess.setText(_translate("XnatDUI", "Sessions"))
        self.rb_subj_res.setText(_translate("XnatDUI", "Resources"))
        self.edt_search_subj.setPlaceholderText(_translate("XnatDUI", "Search SUBJECT label"))
        self.lbl_sess.setText(_translate("XnatDUI", "Select Sessions"))
        self.rb_sess_scans.setToolTip(_translate("XnatDUI", "To download Scan level data"))
        self.rb_sess_scans.setText(_translate("XnatDUI", "Scans"))
        self.rb_sess_res.setToolTip(_translate("XnatDUI", "To download Session Level Resources"))
        self.rb_sess_res.setText(_translate("XnatDUI", "Resources"))
        self.edt_search_sess.setPlaceholderText(_translate("XnatDUI", "Search SESSION Label"))
        self.lbl_scan.setText(_translate("XnatDUI", "Select Scans"))
        self.chk_quality_1.setText(_translate("XnatDUI", "Qlty1"))
        self.chk_quality_2.setText(_translate("XnatDUI", "Qlty2"))
        self.chk_quality_3.setText(_translate("XnatDUI", "Qlty3"))
        self.chk_quality_4.setText(_translate("XnatDUI", "Qlty4"))
        self.chk_quality_5.setText(_translate("XnatDUI", "Qlty5"))
        self.chk_quality_6.setText(_translate("XnatDUI", "Qlty6"))
        self.lbl_resources.setText(_translate("XnatDUI", "Select Resources"))
        self.chk_res_1.setText(_translate("XnatDUI", "Res1"))
        self.chk_res_2.setText(_translate("XnatDUI", "Res2"))
        self.chk_res_3.setText(_translate("XnatDUI", "Res3"))
        self.chk_res_4.setText(_translate("XnatDUI", "Res4"))
        self.chk_res_5.setText(_translate("XnatDUI", "Res5"))
        self.edt_path_txt.setPlaceholderText(_translate("XnatDUI", "Enter text to Send"))
        self.btn_send_edt.setText(_translate("XnatDUI", "Send"))
        self.btn_send_cmb.setText(_translate("XnatDUI", "Send"))
        self.btn_reset_path_all.setText(_translate("XnatDUI", "Reeset All"))
        self.btn_reset_path_selected.setText(_translate("XnatDUI", "Reset Selected"))
        self.chk_path_all_scans.setText(_translate("XnatDUI", "Check/Uncheck All Scans"))
        self.rb_send_path.setText(_translate("XnatDUI", "Send to PATH name"))
        self.rb_send_file.setText(_translate("XnatDUI", "Send to FILE name"))
        self.label.setText(_translate("XnatDUI", "Source"))
        self.label_2.setText(_translate("XnatDUI", "Output-Dir"))
        self.label_3.setText(_translate("XnatDUI", "File-Name"))
        self.label_4.setText(_translate("XnatDUI", "Command"))
        self.grp_down_format.setTitle(_translate("XnatDUI", "Select Format"))
        self.rb_dcm.setText(_translate("XnatDUI", "DICOM"))
        self.rb_afni.setText(_translate("XnatDUI", "AFNI"))
        self.rb_nifti.setText(_translate("XnatDUI", "NIFTI"))
        self.rb_custom.setText(_translate("XnatDUI", "Custom"))
        self.groupBox.setTitle(_translate("XnatDUI", "Conversion Script"))
        self.edt_down_status.setText(_translate("XnatDUI", "Status: Ready"))
        self.btn_refresh_cmd.setText(_translate("XnatDUI", "Refresh"))
        self.btn_download.setText(_translate("XnatDUI", "   DOWNLOAD  "))
        self.rb_up_res_existing.setText(_translate("XnatDUI", "Select Existing Type"))
        self.rb_up_res_new.setText(_translate("XnatDUI", "Create New Type"))
        self.edt_up_res.setPlaceholderText(_translate("XnatDUI", "Enter new RESOURCE Name"))
        self.btn_up_res.setText(_translate("XnatDUI", "Create New Resource"))
        self.btn_upload.setText(_translate("XnatDUI", "UPLOAD"))
        self.btn_export_csv.setText(_translate("XnatDUI", "Export to CSV"))
        self.btn_export_xlsx.setText(_translate("XnatDUI", "Export to XLSX"))
        self.label_8.setText(_translate("XnatDUI", "TextLabel"))
        self.label_9.setText(_translate("XnatDUI", "TextLabel"))
        self.label_10.setText(_translate("XnatDUI", "TextLabel"))
        self.label_0.setText(_translate("XnatDUI", "TextLabel"))
        self.groupBox_5.setTitle(_translate("XnatDUI", "GroupBox"))
        self.groupBox_4.setTitle(_translate("XnatDUI", "GroupBox"))
        self.label_12.setText(_translate("XnatDUI", "Subject"))
        self.edt_search_subB.setPlaceholderText(_translate("XnatDUI", "Search SUBJECT Label"))
        self.label_13.setText(_translate("XnatDUI", "Completion Status"))
        self.edt_search_comp_stat.setPlaceholderText(_translate("XnatDUI", "Search SCAN Label"))
        self.label_14.setText(_translate("XnatDUI", "Scans"))
        self.label_5.setText(_translate("XnatDUI", "Source"))
        self.label_6.setText(_translate("XnatDUI", "Output Directory"))
        self.label_7.setText(_translate("XnatDUI", "Filename"))
        self.btn_res_download.setText(_translate("XnatDUI", "Download"))

